---
- name: Install Alacritty
  ansible.builtin.dnf:
    name: alacritty
    state: latest
  become: true
- name: Install Config Dir
  ansible.builtin.file:
    group: '{{ group }}'
    mode: '0755'
    owner: '{{ owner }}'
    path: '{{ home_directory }}/.config/alacritty'
    state: directory
- name: Copy Config File
  ansible.builtin.copy:
    dest: '{{ home_directory }}/.config/alacritty/alacritty.toml'
    group: '{{ group }}'
    mode: '0644'
    owner: '{{ owner }}'
    src: 'alacritty.toml'
